name: 'PR Metadata Action'
description: 'Adds pull request file changes as a comment to a newly opened PR'
inputs:
  path:
    description: 'Path'
    required: false
    default: "./"
  token:
    description: 'The token to use to access the GitHub API'
    required: false
    default: ${{ github.token }}
runs:
  using: 'node12'
  main: 'dist/index.js'