name: 'Detect PR changes'
description: 'Action to get paths and files changed in a Pull Request event and use these for GitHub Actions matrix'
branding:
  icon: bar-chart
  color: white
inputs:
  path:
    description: 'Path'
    required: false
    default: "./"
  token:
    description: 'The token to use to access the GitHub API'
    required: false
    default: ${{ github.token }}
outputs:
  paths_list:
    description: 'List of changed paths, example: `["dist", "dist/data"]`'
  file_list:
    description: 'List of changed files, example: `["dist/main.tf", "dist/index.js"]`'
  paths_str:
    description: 'List of changed paths separated by `,` example: `"dist,dist/data"`'
  file_str:
    description: 'List of changed files separated by `,` example: `"dist/main.tf,dist/index.js"`'
runs:
  using: 'node16'
  main: 'dist/index.js'
